# Generated by Django 2.2.13 on 2020-06-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200607_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentAuthor',
            new_name='author',
        ),
    ]
