# Generated by Django 2.2.13 on 2020-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200607_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
